# RNN Implementation from Scratch

## Import Libraries

In [37]:
import numpy as np

## Import Data

In [38]:
# Create a NumPy array from the values
data = np.array([66, 70, 62, 65])

# Select the first three values into a variable named temps
temps = data[:3]

In [39]:
print("Data: ",data)
print("Input: ",temps)

Data:  [66 70 62 65]
Input:  [66 70 62]


## Forward Pass

### Initialize Weights

In [40]:
np.random.seed(0)

input_weights = np.random.rand(1,2)

hidden_weights = np.random.rand(2,2)
hidden_bias = np.random.rand(1,2)

output_weights = np.random.rand(2,1)
output_bias = np.random.rand(1,1)

In [41]:
print("Input Weights: ",input_weights)
print("Hidden Weights: ",hidden_weights)
print("Hidden Bias: ",hidden_bias)
print("Output Weights: ",output_weights)
print("Output Bias: ",output_bias)

Input Weights:  [[0.5488135  0.71518937]]
Hidden Weights:  [[0.60276338 0.54488318]
 [0.4236548  0.64589411]]
Hidden Bias:  [[0.43758721 0.891773  ]]
Output Weights:  [[0.96366276]
 [0.38344152]]
Output Bias:  [[0.79172504]]


### Apply Weights

In [43]:
# An array to store the output predictions
outputs = np.zeros(3)
# An array to store hidden states for use in backpropagation
hiddens = np.zeros((3, 2))

# This will store the previous hidden state, since we'll need it to calculate the current hidden step
prev_hidden = None
sequence = temps

for i in range(3):
    # Get the input sequence at the given position
    x = sequence[i].reshape(1,1)

    # Multiply input by input weight
    xi = x @ input_weights
    if prev_hidden is not None:
        # Add previous hidden to input
        xh = xi + prev_hidden @ hidden_weights + hidden_bias
    else:
        xh = xi

    # Apply our activation function
    xh = np.tanh(xh)
    prev_hidden = xh
    hiddens[i,] = xh

    # Multiply by the output weight
    xo = xh @ output_weights + output_bias
    outputs[i] = xo

### Outputs

In [44]:
outputs

array([2.13882932, 2.13882932, 2.13882932])

In [45]:
hiddens

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Calculate Loss

In [48]:
def loss(actual, predicted):
    return (predicted - actual)

In [49]:
# Actual next day temperatures
actuals = np.array([70, 62, 65])

loss_values = loss(actuals, outputs)
loss_values

array([-67.86117068, -59.86117068, -62.86117068])